/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package window;

import Tools.Image.ImageTools;
import Tools.face.DetectFace;
import com.arcsoft.face.FaceFeature;
import com.arcsoft.face.FaceInfo;
import com.arcsoft.face.Rect;
import entity.User;
import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import sun.awt.image.ToolkitImage;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class RegistFrm extends JFrame {

    /**
     * Creates new form MainFrm
     */
    private User user;
    private Image image=null;
    private File imgFile=null;
    private String imgName="";
    private byte[] faceData;
    static private SqlSession sqlSession=null;

    static {
        String resources="sqlMappingConfig.xml";
        InputStream inputStream= null;
        try {
            inputStream = Resources.getResourceAsStream(resources);
        } catch (IOException e) {
            e.printStackTrace();
        }
        SqlSessionFactory sqlSessionFactory=new SqlSessionFactoryBuilder().build(inputStream);
        sqlSession=sqlSessionFactory.openSession();
    }
    public RegistFrm(){
        //初始化识别引擎
        DetectFace.faceEngine_init();
        initComponents();
        jTextField2.setEditable(false);                         //将文件名设置为不可修改
        jLabel7.setIcon(getShowIcon("F:\\AI酒店\\SDK的test图片\\backgrounImg.png")); // NOI18N

        int c =sqlSession.selectOne("getUserCount");
        System.out.println("当前用户数："+c);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    //该方法实现自动调整image的大小
    private ImageIcon getShowIcon(String img){
        ImageIcon img_icon= new ImageIcon(img);
        System.out.println(jLabel7.getWidth()+"  "+jLabel7.getHeight());
        img_icon.setImage(img_icon.getImage().getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(),Image.SCALE_DEFAULT));
        return img_icon;
    }
    private ImageIcon getShowIcon(Image img){
        ImageIcon img_icon= new ImageIcon(img);
        img_icon.setImage(img_icon.getImage().getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(),Image.SCALE_DEFAULT));
        return img_icon;
    }
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        jFrame1 = new JFrame();
        jFileChooser1 = new JFileChooser();
        jButton1 = new JButton();
        jButton4 = new JButton();
        jPanel1 = new JPanel();
        jLabel4 = new JLabel();
        jTextField1 = new JTextField();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTextPane1 = new JTextPane();
        jLabel2 = new JLabel();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jLabel3 = new JLabel();
        jPanel2 = new JPanel();
        jSeparator1 = new JSeparator();
        jLabel6 = new JLabel();
        jPanel3 = new JPanel();
        jLabel7 = new JLabel();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jLabel5 = new JLabel();
        jTextField2 = new JTextField();
        jLabel8 = new JLabel();

        GroupLayout jFrame1Layout = new GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFileChooser1.setCurrentDirectory(new File("F:\\AI酒店\\SDK的test图片"));

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("用户注册");
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setLocation(new Point(450, 250));

        jButton1.setText("提交信息");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jButton4.setText("返回");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(BorderFactory.createEtchedBorder());

        jLabel4.setText("电话号码：");

        jLabel1.setText("用户姓名：");

        jScrollPane1.setViewportView(jTextPane1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("男");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("女");

        jLabel3.setText("性别：");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                )
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(BorderFactory.createEtchedBorder());

        jLabel6.setText("选择图片或拍照：");

        jPanel3.setBorder(BorderFactory.createEtchedBorder(Color.cyan, null));
        //        jLabel7.setIcon(new ImageIcon("F:\\AI酒店\\SDK的test图片\\backgrounImg.png"));
        jLabel7.setText("jLabel7");


        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 84, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
        );


        jButton2.setText("打开文件");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("打开相机");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel5.setText("文件名：");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel8.setText("预览：");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)))
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 299, GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 354, Short.MAX_VALUE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, IOException {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:    提交按键

        String warn = "";
        int f = 0;

        if("".equals(jTextPane1.getText().trim())||jTextPane1.getText()==null){
            f+=1;
        }
        if(image==null){
            f+=2;
        }
        if(f!=0){       //如果输入结果异常，则清空并退出
            if(f==1) {
                jTextPane1.setText("");
                warn= "请输入有效的名字";
                }
            if(f==2){
                warn="请选择或者拍摄一张含有人脸的标准图片";
            }
            if(f==3){
                jTextPane1.setText("");
                warn="请输入姓名，并且上传一张有效的人脸图像";
            }
            JOptionPane.showMessageDialog(null,warn);
            return;
        }
        //如果无异常则提交数据库，并且提示成功并退出
        String path="F:\\AI酒店\\SDK的test图片\\系统人脸图片";

        //写入图片到本地路径
        imgName = jTextField2.getText();

        if(image instanceof ToolkitImage)       //注意：用文件选择器打开的文件格式 为 ToolkitImage
        image = ((ToolkitImage)image).getBufferedImage();
        ImageIO.write((BufferedImage) image,"jpg",new File(path+"\\"+imgName));

        user = new User();
        user.setUser_name(jTextPane1.getText());    //获去用户名
        if(jRadioButton1.isSelected()) user.setGender("男"); //获取性别
        else user.setGender("女");
        String phone = jTextField1.getText();
        user.setPhone(phone);   //电话
        String faceFeature="";
        //获取人脸二进制数据 ,以字符串转存
        FaceFeature feature = DetectFace.detectFace(image);//获取脸部特征数据
        faceData = feature.getFeatureData();

        for(byte a : faceData){
            faceFeature = faceFeature + a + ".";
        }
        user.setFace_feature(faceFeature);
        String pathTemp = path;
        user.setImg_name(imgName);  //文件名
        user.setImg_path(path);     //路径
        int rs =  sqlSession.insert("addUser",user);
        sqlSession.commit();
        if(rs>0){
            System.out.println("提交成功");
            DetectFace.exitEngine();    //关闭识别引擎
            this.dispose();     //成功之后关闭 窗口

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:    返回
        dispose();
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }

    //从文件系统中选取
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FileFrm frm = new FileFrm();

        FileFilter fileFilter = new FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory()) return true;
                if(f.getName().toLowerCase().endsWith(".jpg")||
                        f.getName().toLowerCase().endsWith(".png")||
                        f.getName().toLowerCase().endsWith(".bmp")||
                        f.getName().toLowerCase().endsWith(".jpeg")
                )return true;
                return false;
            }
            @Override
            public String getDescription() {
                return ".jpg/.jpeg/.png/.bmp";
            }
        };
        jFileChooser1.setFileFilter(fileFilter);        //注意：添加文件过滤器 等对文件选择器的修改操作一定要放在显示操作的前面，不然可能会失效
        int returnVal = jFileChooser1.showOpenDialog(frm);

        if(returnVal == JFileChooser.APPROVE_OPTION) {
        //获取文件
        imgFile = jFileChooser1.getSelectedFile();//获取选中的文件


        //修改预览图像

        ImageIcon icon=new ImageIcon(imgFile.getPath());

        image = icon.getImage();    //缓存选择的图片
        //引擎识别一下，是否有人脸
        List<FaceInfo> faceInfo = DetectFace.getFaceInfo(image);
        if(faceInfo==null){     //当检测没有人脸时，设置为标准背景图片
            ImageIcon icon1 = new ImageIcon("F:\\AI酒店\\SDK的test图片\\背景.png");
            icon1.setImage(icon1.getImage().getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(),Image.SCALE_DEFAULT));
            jLabel7.setIcon(icon1);
            image=null;
            jTextField2.setText("");
            return;
        }
        icon.setImage(icon.getImage().getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(),Image.SCALE_DEFAULT));
        jLabel7.setIcon(icon);
        jTextField2.setText(imgFile.getName());     //设置文件名框体的内容
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws InterruptedException {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        final CapFrm capFrm = new CapFrm();
        capFrm.setVisible(true);
        capFrm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if(!capFrm.isSave&&capFrm.btn_cap.getText().equals("重拍")){    //检测到没有保存
                    int result = JOptionPane.showConfirmDialog(null,"没有保存，是否保存？",
                            "提示",JOptionPane.OK_CANCEL_OPTION);
                    if(result== JOptionPane.OK_OPTION){
                        capFrm.isSave = true;
                    }
                }
                if(capFrm.isSave){
                    //识别出face
                    image = capFrm.getImage();
                    Rect rect =  DetectFace.getFaceLocation(image);

                    //获取Label的尺寸
                    int reImgWidth = jLabel7.getWidth();
                    int reImgHeight = jLabel7.getHeight();
                    if(rect==null){//操作图片前检测是否有人脸
                        image=null;
                        ImageIcon icon=new ImageIcon("F:\\AI酒店\\SDK的test图片\\背景.png");
                        jTextField2.setText("");
                        icon.setImage(icon.getImage().getScaledInstance(reImgWidth,reImgHeight,Image.SCALE_DEFAULT)); //图片适应窗口宽度
                        jLabel7.setIcon(icon);  //显示图像
                        return;
                    }

                    //剪切图片
                    image = ImageTools.cutImg(image,rect);

                    ImageIcon icon=new ImageIcon(image);
                    icon.setImage(image.getScaledInstance(reImgWidth,reImgHeight,Image.SCALE_DEFAULT)); //图片适应窗口宽度
                    jLabel7.setIcon(icon);  //显示图像
                    int count = sqlSession.selectOne("getUserCount");
                    count++;
                    String name="face_"+count+".jpg";
                    jTextField2.setText(name);     //设置文件名框体的内容
                    System.out.println("保存成功！");
                }
                capFrm.webcam.close();
                capFrm.dispose();
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JFileChooser jFileChooser1;
    private JFrame jFrame1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
//    private javax.swing.JPasswordField jPasswordField1;
    private JRadioButton jRadioButton1; //男
    private JRadioButton jRadioButton2; //女
    private JScrollPane jScrollPane1;
    private JSeparator jSeparator1;
    private JTextField jTextField1; //phone
    private JTextField jTextField2; //filename
    private JTextPane jTextPane1;       //username

    // End of variables declaration//GEN-END:variables

}
